config/routes.rb
Rails.application.routes.draw do
  #admin
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  namespace :admin do
    root 'homes#top', as: :root
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  	resources :orders, only: [:show,:update]
    resources :order_details, only: [:update]
  end
  #public
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'publics/passwords',
    registrations: 'public/registrations'
  }
    root to: 'public/homes#top'
    get 'about' => 'public/homes#about'
    scope module: :public do
      resources :items, only: [:index, :show]
      resource :customers, only: [:show, :edit, :update] do
        collection do
          get 'quit'
          patch 'out'
        end
      end
      resources :cart_items, only: [:index, :update, :destroy, :create] do
        collection do
          delete 'all_destroy'
        end
      end
      resources :orders, only: [:new, :create, :index, :show] do
        collection do
          post 'confirm'
          get 'thanks'
        end
      end
      resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]
    end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :customer_id, :name, :address, presence: true
  validates :postal_code, length: { is: 7 }, numericality: { only_integer: true }
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  validates :item_id, presence: true
  #validates :customer_id, presence: true
  validates :amount, numericality:{ only_integer: true }

  # 小計を求めるメソッド
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_address, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :postal_code, numericality: {only_integer: true}, format: {with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}$|^\d{5}$|^\d{7}\z/}
  validates :telephone_number, numericality: { only_integer: true }

  def active_for_authentication?
    super && (self.is_active == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :orders
  has_many :order_details, dependent: :destroy
  attachment :image

  validates :genre_id, :name, :introduction, presence: true
  validates :price, numericality: { only_integer: true }
  
  ## 消費税を求めるメソッド
  def with_tax_price
      (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :customer_id, :address, :name, presence: true
  validates :postal_code, length: { is: 7 }, numericality: { only_integer: true }
  validates :shipping_cost, :total_payment, numericality: { only_integer: true }

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { unpaid: 0, paid: 1, making: 2, preparation: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  validates :item_id, :order_id, presence: true
  validates :price, :amount, numericality: { only_integer: true }

  enum making_status: { notmaking: 0, standby: 1, making: 2, finish: 3 }
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :shipping_address, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :address, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :postal_code, numericality: {only_integer: true}, format: {with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}$|^\d{5}$|^\d{7}\z/}
  validates :telephone_number, numericality: { only_integer: true }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top #管理者トップページ(注文履歴一覧)
    @orders = Order.all.page(params[:page]).reverse_order
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "新商品を登録しました"
    redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品内容を変更しました"
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters , if: :devise_controller?

    protected

        #ログイン後のリダイレクト先
        def after_sign_in_path_for(resource)
            case resource
            when current_customer
                customers_path(resource)
            when current_admin
                admin_root_path
            end
        end

        #ログアウト後のリダイレクト先
        def after_sign_out_path_for(resource)
            # case resource
            # when :customer
            #     new_customer_session_path
            # when :admin
            #     new_admin_session_path
            # end
            if resource == :admin
                new_admin_session_path
            else
                new_customer_session_path
            end
        end


        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up,
            keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number])
            devise_parameter_sanitizer.permit(:account_update,
            keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number])
        end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/oder_details_helper.rb
module Admin::OderDetailsHelper
end

app/helpers/admin/oders_helper.rb
module Admin::OdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_admin_navbar.html.erb
<header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>NAGANO CAKE -管理者ページ-</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li>
                <%= link_to "注文履歴一覧", admin_root_path, class: "text-light px-2" %>
              </li>
              <li>
                <%= link_to "商品一覧", admin_items_path, class: "text-light px-2" %>
              </li>
              <li>
                <%= link_to "ジャンル管理画面", admin_genres_path, class: "text-light px-2" %>
              </li>
              <li>
                <%= link_to "顧客一覧", admin_customers_path, class: "text-light px-2" %>
              </li>
              <li>
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "text-light px-2" %>
              </li>
            <% else %>
              <li>
                <%= link_to "ログイン", new_admin_session_path, class: "text-light px-2" %>
              </li>
            <% end %>
          </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/_public_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to image_tag("logo.png"), root_path %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <% if customer_signed_in? %>
      　<ul class="navbar-nav mr-auto">
          <li>ようこそ、<%= current_customer.last_name %><%= current_customer.first_name %>さん！</li>
        </ul>
        <ul class="navbar-nav">
          <li>
            <%= link_to "マイページ", customers_path(current_customer), class: "text-secondary px-2" %>
          </li>
          <li>
            <%= link_to "商品一覧", items_path, class: "text-secondary px-2" %>
          </li>
          <li>
            <%= link_to "カート", cart_items_path, class: "text-secondary px-2" %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "text-secondary px-2" %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li>
            <%= link_to "新規登録", new_customer_registration_path, class: "text-secondary px-2" %>
          </li>
          <li>
            <%= link_to "ログイン", new_customer_session_path, class: "text-secondary px-2" %>
          </li>
          <li>
            <%= link_to "商品一覧", items_path, class: "text-secondary px-2" %>
          </li>
        </ul>
      <% end %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
            </form>
          </li>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <br><br>
    <footer class="bg-light text-dark pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>NAGANO CAKE</p>
          </div>
          <div class="col-md-8">
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-dark">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-dark">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>